---
- name: Update apt
  apt: update_cache=yes

- name: Install common tools
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - git-core
    - vim
    - curl
    - mc
    - python-pycurl
    - software-properties-common
    - htop
    - build-essential

- name: Install extra tools
  apt:
    name: "{{ item }}"
    state: latest
  with_items: tools_present

- name: Set default locale
  apt:
    name: language-pack-en
    update_cache: yes

- name: Set timezone variables
  copy:
    content: '{{ env_timezone }}\n'
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Intsall unatennded upgrade package
  apt:
    name: unattended-upgrades
    update_cache: yes

- name: Setup unattended upgrade configuration
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Setup unattended upgrade configuration periodic
  template:
    src: 10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic