---
php_extensions:
  - php7.0-cli
  - php7.0-gd
  - php7.0-pgsql
  - php7.0-mongodb
  - php7.0-mysql
  - php7.0-curl
  - php7.0-intl
  - php7.0-mcrypt
  - php7.0-dev
  - php7.0-xml
  - php7.0-mbstring
  - php7.0-bcmath
  - php-pear

php_ini_lines: []
