---
- name: Add PHP 7.0 repo
  apt_repository: >
    repo=ppa:ondrej/php
    update_cache=true
  when: ansible_os_family == 'Debian'

- name: Install PHP
  apt: name=php7.0 state=latest

- name: Intsall PHP packages
  apt: name={{ item }} state=present
  with_items: php_extensions

- name: Install apache2 php7 module
  apt:
    name: libapache2-mod-php7.0
    state: latest
    update_cache: true

- name: Register apache php.ini directory state
  stat:
    path: /etc/php/7.0/apache2/conf.d
  register: php70_ini_apache

- name: Configure PHP APACHE
  template:
    src: php_config.ini.j2
    dest: /etc/php/7.0/apache2/conf.d/php_config.ini
  when: php70_ini_apache.stat.isdir is defined and php70_ini_apache.stat.isdir

- name: Register CLI php.ini directory state
  stat:
    path: /etc/php/7.0/cli/conf.d
  register: php70_ini_cli

- name: Configure PHP CLI
  template:
    src: php_config.ini.j2
    dest: /etc/php/7.0/cli/conf.d/php_config.ini
  when: php70_ini_cli.stat.isdir is defined and php70_ini_cli.stat.isdir

- name: Register FPM php.ini directory state
  stat:
    path: /etc/php/7.0/fpm/conf.d
  register: php70_ini_fpm

- name: Configure PHP FPM
  template:
    src: php_config.ini.j2
    dest: /etc/php/7.0/fpm/conf.d/php_config.ini
  when: php70_ini_fpm.stat.isdir is defined and php70_ini_fpm.stat.isdir

